### ISSUE TITLE
Please merge themes

### ISSUE THREAD

**Issue by Gaohaoyang** [mattvh/jekyllthemes#118]
It is a long time after you merged pull requests last time. May be you are busy. If you have time, please merge 13 new themes.

I'd glade to see that.

**Comment by jacobtomlinson** [comment]
:+1:

**Comment by Gaohaoyang** [comment]
So where is the author of this repository?
@jacobtomlinson Do you konw?

**Comment by jacobtomlinson** [comment]
Not a clue I'm afraid, I reached out to him on Twitter but no luck!

**Comment by jacobtomlinson** [comment]
@mattvh it has been over two months since you last merged any PRs on this repo. If you're struggling to find time then I would like to offer my help, I'm happy to review PRs for you (and ensure the same standards that you do) as well as keeping the site up to date and even implementing some of the things I mentioned in #104.

I'm sure lots of people would agree that this is a good idea!

@mx3m @Gaohaoyang @diezcami @karloespiritu @DigitalMindCH @smallmuou @SpaceG @mushishi78 @nmenag @kevit @qckanemoto @arniekoz @ariestiyansyah @parkr

**Comment by Gaohaoyang** [comment]
# Absolutely Agree!

**Comment by DigitalMindCH** [comment]
we would be pretty glad as well!

**Comment by karloespiritu** [comment]
Sounds good and I completely agree! :beers:

**Comment by ariestiyansyah** [comment]
Agree with @jacobtomlinson , We can help maintai this repo. 

Anyway if we dont get update from @mattvh I suggest to create new site, I can buy new domain if you need.

cc @mx3m @Gaohaoyang @diezcami @karloespiritu @DigitalMindCH @smallmuou @SpaceG @mushishi78 @nmenag @kevit @qckanemoto @arniekoz @parkr

**Comment by parkr** [comment]
There was some talk about moving this to the jekyll org, but that has not happened yet.

**Comment by jacobtomlinson** [comment]
@ariestiyansyah I agree and the same thought had crossed my mind.

@parkr would it be possible to fork this repository into the jekyll org and host it on github pages under themes.jekyllrb.com? Then setup myself, @mattvh and @ariestiyansyah with push access? I'm happy to spend some time updating the website itself and bringing it in line with the rest of the jekyll website.

**Comment by Phlow** [comment]
I think this would be great. I was lucky that @mattvh updated the website. It gave my theme a lot of boost and interested people. Without jekyllthemes.org that would have not happened. I would advise to make a themes.jekyllrb.com website.

It's the best thing to drive even more people into Jekyll and make them to use it. I am an admirer of how Automattic pushed WordPress by building a community site like wordpress.org. For me as a – at best – mediocre programmer the starting point developing with a new tool is to look at other peoples work. That's the power of open source. And if Matt has no time for this project, it would be great if people like @jacobtomlinson help out.

**Comment by diezcami** [comment]
I'd be happy to help out as well - I could help merge pull requests and perhaps tweak the current layout, if you guys don't mind.

**Comment by Gaohaoyang** [comment]
@ariestiyansyah It's a great idea. 

I can help review codes too. We can do together and make it better!
Then Jekyll themes will be popular. What an exciting work!

**Comment by ariestiyansyah** [comment]
Just requested sub-domain from jekyllrb creator, I'll update when I get good news.

**Comment by Gaohaoyang** [comment]
Nice

**Comment by smallmuou** [comment]
Thank you so much!!!

发自我的 iPhone

**Comment by ariestiyansyah** [comment]
Please check the discussion in this issue https://github.com/jekyll/jekyll/issues/3749

**Comment by ddbullfrog** [comment]
Absolutely Agree!

**Comment by ariestiyansyah** [comment]
Since the discussion on https://github.com/jekyll/jekyll/issues/3749 is closed I decided to send email to @parkr asking about subdomain or create new site. 

If Jekyll can't provide the subdomain let's poll for new domain and I'll create the repository of it

1. jekyllthemes.com
2. jekyll-themes.org
3. jekyll-themes.com
4 Suggest your idea

**Comment by Phlow** [comment]
I vote for jekyll-themes.org.

- You can read it well.
- **.COM** stands for commercial... It's more of an open source project, right ;)

**Comment by smallmuou** [comment]
Agree  jekyll-themes.org

**Comment by ddbullfrog** [comment]
Agree  jekyll-themes.org

Pawpaw <notifications@github.com>于2015年6月2日星期二写道：

**Comment by ariestiyansyah** [comment]
I see it's good domain name, I'll buy the doman in Thursday or Friday. At this I try move the code to new repository here https://github.com/ariestiyansyah/jekyllthemes and plan to change the web design. Please start contribute to the new repo.

**Comment by smallmuou** [comment]
Ok, I will start contribute to the new repo.                             Original Message                             Sender: Rizky Ariestiyansyah<notifications@github.com>Recipient: mattvh/jekyllthemes<jekyllthemes@noreply.github.com>Cc: Pawpaw<lvyexuwenfa100@126.com>Date: Tuesday, Jun 2, 2015 19:45Subject: Re: [jekyllthemes] Please merge themes (#118)I see it's good domain name, I'll buy the doman in Thursday or Friday. At this I try move the code to new repository here https://github.com/ariestiyansyah/jekyllthemes and plan to change the web design. Please start contribute to the new repo.

**Comment by jacobtomlinson** [comment]
Yep me too!

**Comment by jacobtomlinson** [comment]
You should start by pulling in the open PRs from mattvh/jekyllthemes. And it would be good to have more than one person with push access to your repo, to avoid this from happening again.

Could you please give me push access.

**Comment by ariestiyansyah** [comment]
Done @jacobtomlinson 

Pleae move all the conversation to https://github.com/ariestiyansyah/jekyllthemes/issues/2

**Comment by parkr** [comment]
Did anyone try talking to @mattvh?

**Comment by ariestiyansyah** [comment]
@parkr Some of us are contacted him but no respond, anyway please respond to my email so we get answer if we can start themes.jekyllrb.com or not (create another one)

**Comment by jacobtomlinson** [comment]
@parkr yeah I've tried multiple times through GitHub, Twitter and email.

**Comment by mattvh** [comment]
Sorry I've been so out of contact lately. I was busy, then sick for three weeks. I'll try to get things merged back up soon.

**Comment by mattvh** [comment]
Ok done.

**Comment by jacobtomlinson** [comment]
@mattvh great to see you're back! Hope you're feeling better.

It would be great if this could be avoided in future, I notice that it isn't the first time that PRs have been left for a few months. Would you consider letting someone else help you out?

**Comment by jacobtomlinson** [comment]
?

**Comment by erlend-sh** [comment]
@mattvh available again these days? Please add @jacobtomlinson , @ariestiyansyah and @gynter as contributors.

**Comment by gynter** [comment]
No clue, haven't had any contact from him.

**Comment by jacobtomlinson** [comment]
This happens regularly, @mattvh only checks this repo every couple of months. It's a shame because I think this project would be even better if it was maintained properly. @gynter has done some excellent work on it and greatly improved it, and yet even he hasn't been made a contributor with merge permissions.

@geraldb has started a competing project called [Dr Jekyll's Themes](https://drjekyllthemes.github.io/) and he appears to maintain it very well. Personally I disagree with his move away from pure Jekyll for the project but it is probably a better option than this one now.

[jekyllthemes.io](http://www.jekyllthemes.io/) looks really nice but doesn't appear to be open source and puts more emphasis on selling premium themes.

**Comment by geraldb** [comment]
Hello, FYI: Dr Jekyll's Themes is NOT competing. It's just another alternative. (it's different e.g. includes a theme package manager and a script wizard etc. and some more). The site is a "pure" GitHub Pages (Jekyll) site. To make it easier to contribute it uses a gitsubmodule for /themes   All code incl. "the build (pre-processing) step" (see the /build repo) is open and public domain. Cheers. PS: The themes.yml file is designed for easy (re)use - similar to the static site listing, for example, see [bevry/staticsitegenerators-list](https://github.com/bevry/staticsitegenerators-list). Cheers. 
PS: I'd say just fork the jekyllthemes repo (your're two or three ?) and move your copy to themes.jekyllrb.com, for example. What's holding you back? Just my two cents.

**Comment by jacobtomlinson** [comment]
Great thanks for the clarification. I was referring to the fact that it requires a build script and that you can't fork the repo and have it would just work with GitHub Pages without some extra configuration and creation/maintaining of build servers.

We (@ariestiyansyah and I) already tried forking the repo but a few days after we did @mattvh came back, merged everything on here and assured us he would merge more often. We also spoke to @parkr about themes.jekyllrb.com and he basically said a lot will change with Jekyll 3's themes and plugins and that he wanted to hold off on that for now.

**Comment by erlend-sh** [comment]
> PS: I'd say just fork the jekyllthemes repo (your're two or three ?) and move your copy to themes.jekyllrb.com, for example. What's holding you back? Just my two cents.

One problem is that in this case themes.jekyllrb.com will compete with jekyllthemes.org for Google ranking, and there will be Yet Another Themes Site on the web competing for users' attention. Right now, jekyllthemes.org is very established. It would be much better if it could be continuously maintained by a group of Jekyll contributors for a while, and *then* be migrated (and redirect to) themes.jekyllrb.org in due time.

**Comment by gynter** [comment]
I agree with @erlend-sh, another fork would just bring up more confusion.

@jacobtomlinson I don't see why the page couldn't be built via Github pages. It seems to be work fine when testing with `jekyll serve` on 2.4.0. I created a separate issue about that: #188.

**Comment by jacobtomlinson** [comment]
@gynter I was talking about Dr Jekyll's Themes not this one :smile:.

And yes I agree with @erlend-sh.

**Comment by geraldb** [comment]
Just one more time: Be bold, stop talking and complaining. Show us how to to do it. Lead by example and action. Do NOT worry about the google ranking. If you work hard the new directory will rise up. It's that easy ;-)  There's no confusion. Let's welcome and celebrate more theme directories. PS: If you use a public domain "un-license"  it's easy to keep the yaml listing in sync, for example and so on. After all it's just data. Cheers.

**Comment by mushishi78** [comment]
I made a fork: [themes-jekyll.github.io](http://themes-jekyll.github.io/)

I re-wrote the site from scratch with the following changes:

* Uses `jekyll-sitemap` and `jekyll-feed`.
* Uses jekyll compiled sass, rather than pre-compiling less
* Compressed HTML layout
* Removed extraneous images and bootstrap assets
* Slightly smoother responsive breakpoints
* More semantic markup, less style classes
* More succinct templates, less arbitrary new lines.
* `html5shiv` and `respond.min` for old ie8
* No advert as hosted on GitHub pages
* Nav links with clearer link to github page
* Index pages for alphabetical order and divided by author
* Infinite list rather then pagination, with contributing explanation in footer moved to new page

I've left `thumbnails` and `_posts` untouched so pull request on this repo can merged in without much trouble. If anyone wants to be a contributor they're more than welcome.

I appreciate that it's a lost cause trying to rank a new site if we're going to move onto themes.jekylrb.com. However, perhaps there's something to @geraldb's notion of "leading by example". @mattvh can always merge changes back in if he wants, and group repository could serve as a better starting point before making the move over to the official domain.

**Comment by erlend-sh** [comment]
Okay, that's a pretty convincing argument there @mushishi78 , nice work! :clap: 

I could get on board with supporting that fork. Like you said, it can always be merged back in, which would ideally coincide with the addition of some new contributors.

**Comment by mushishi78** [comment]
@erlend-sh @jacobtomlinson @gynter @ariestiyansyah I've presumptuously given you guys write access, if you don't want to be involved, feel free to ignore it.

I've also added an experimental preview demos page, that can be removed if no-one wants likes it.

**Comment by geraldb** [comment]
@mushishi78  Great initiative. Keep it up. Will try to promote the new theme directory e.g. [first tweet here](https://twitter.com/viennahtml/status/640780859646328832). Cheers.

**Comment by mushishi78** [comment]
For anyone on this thread whose interested, the new fork has been moved to [jekyllrc/jekyllthemes](https://github.com/jekyllrc/jekyllthemes) as @gynter wanted to have an umbrella organisation to manage other jekyll projects that might need forking.

Thanks @geraldb for your promotion :)

**Comment by ariestiyansyah** [comment]
Cool, let's do the best!

On Mon, Sep 7, 2015 at 6:53 PM, Max White <notifications@github.com> wrote:

> For anyone on this thread whose interested, the new fork has been moved to
> jekyllrc/jekyllthemes <https://github.com/jekyllrc/jekyllthemes> as
> @gynter <https://github.com/gynter> wanted to have an umbrella
> organisation to manage other jekyll projects that might need forking.
>
> Thanks @geraldb <https://github.com/geraldb> for your promotion :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mattvh/jekyllthemes/issues/118#issuecomment-138278493>
> .
>



-- 
*Rizky Ariestiyansyah*
Business Consultant
Enterprise Solution and Mobile Development
Personal Website: http://oonlab.com/about/
Phone : +6287804020496 | Time zone: GMT+7
