### ISSUE TITLE
Template or Theme

### ISSUE THREAD

**Issue by HUDevelopmentClub** [mattvh/jekyllthemes#212]
I am new to jekyll and was wondering if these are templates or installable themes?

**Comment by gynter** [comment]
Welcome to the Jekyll world! :)

Jekyll hasn't got any templating/theming system, those are basically fully working page layouts. Some of those also have some example content. To install any of those You should extract the contents of the archive to the root directory of Your Jekyll page. Be aware with overwriting thou, since sometimes example content could overwrite already Your existing content. Also, please post further questions to Jekyll forum https://talk.jekyllrb.com which has more people following it so You might get a better answer to Your questions.

With kind regards,
G.
