### ISSUE TITLE
Add Gemfile

### ISSUE THREAD

**Issue by nandomoreirame** [mattvh/jekyllthemes#252]
Add Gemfile to fix Ruby and Jekyll installation version...

**Comment by gynter** [comment]
PRs are welcome :smile: I'll look into it if I get a bit of free time.

**Comment by nandomoreirame** [comment]
@gynter look this PR #348 ;)

**Comment by jiehu567** [comment]
Hi, I got this error when using: jekyll server
Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
jekyll 3.3.0 | Error:  jekyll-paginate

I tried google out what to do, but still have no idea. Any suggestions are welcome.

Tnx,

Jie
