### ISSUE TITLE
Is there nobody maintain this repository?

### ISSUE THREAD

**Issue by panxw** [mattvh/jekyllthemes#462]
PRs are not merged from a month ago!

**Comment by dikiaap** [comment]
the owner is not active and there's @gynter as collaborator, but idk.

**Comment by mattvh** [comment]
We're working on it. I've been a little bit more absent lately than I'd like due to work and stuff, but have already knocked a few merges.

I would be open to adding another collaborator if need be, if @gynter has anyone in mind who stands out.

**Comment by geraldb** [comment]
@panxw  I'd say why not try alternatives such as Dr. Jekyll's -> http://drjekyllthemes.github.io  that are kept up-to-date (incl. more new themes too ;-) e.g. all the lastest pages themes from GitHub etc.) Cheers.

**Comment by panxw** [comment]
@geraldb you are right,  I will move it.

**Comment by jarrekk** [comment]
Hi, since we haven't seen this repository's owner for a very long time, I forked it to my [repo](https://github.com/jarrekk/jekyll-theme) and built this website with a new **domain name**:
 <http://jekylltheme.org>.

Anyone's theme who submitted it before will still be seen at <http://jekylltheme.org> and welcome everyone to contribute this website if you have nice themes.

Later I will beautify this repository to make it better, an excellent website needs everyone's contribution/PR too!😊
