### ISSUE TITLE
HCZ Jekyll Material

### ISSUE THREAD

**Issue by ZeevoX** [mattvh/jekyllthemes#493]
[HCZ Jekyll Material Theme](http://jekyllthemes.org/themes/hcz-jekyll-material/) does not have a working live demo.

**Comment by RioSatria** [comment]
The master file have working demo, as you can see from this file
https://github.com/mattvh/jekyllthemes/blob/master/_posts/2016-06-05-hcz-jekyll-material.markdown

The reason why the link won't work because the site fail to built.
For more info see: https://github.com/mattvh/jekyllthemes/issues/494#issuecomment-314692125

**Comment by jarrekk** [comment]
Hi, since we haven't seen this repository's owner for a very long time, I forked it to my [repo](https://github.com/jarrekk/jekyll-theme) and built this website with a new **domain name**:
 <http://jekylltheme.org>.

Anyone's theme who submitted it before will still be seen at <http://jekylltheme.org> and welcome everyone to contribute this website if you have nice themes.

Later I will beautify this repository to make it better, an excellent website needs everyone's contribution/PR too!😊

**Comment by jarrekk** [comment]
Hi, since we haven't seen this repository's owner for a very long time, I forked it to my [repo](https://github.com/jarrekk/jekyll-theme) and built this website with a new **domain name**:
 <http://jekylltheme.org>.

Anyone's theme who submitted it before will still be seen at <http://jekylltheme.org> and welcome everyone to contribute this website if you have nice themes.

Later I will beautify this repository to make it better, an excellent website needs everyone's contribution/PR too!😊

**Comment by artlogic** [comment]
Demo is working fine now.
