### ISSUE TITLE
Repository was migrated to new place

### ISSUE THREAD

**Issue by jarrekk** [mattvh/jekyllthemes#502]
Hi, since we haven't seen this repository's owner for a very long time, I forked it to my [repo](https://github.com/jarrekk/jekyll-theme) and built this website with a new **domain name**:
 <http://jekylltheme.org>.

Anyone's theme who submitted it before will still be seen at <http://jekylltheme.org> and welcome everyone to contribute this website if you have nice themes.

Later I will beautify this repository to make it better, an excellent website needs everyone's contribution/PR too!😊

**Comment by InsidiousMind** [comment]
Awesome! Was wondering what happened to this site. Sucks that the owner is gone, but hopefully this new site will gain traction quick! :-)

**Comment by mattvh** [comment]
I'm still around, just dealing with some personal issues lately. And I'd much rather add additional contributors than encourage fragmentation.

**Comment by jarrekk** [comment]
@mattvh If possible, please add me to this repo's collaborators, many thanks :)

**Comment by InsidiousMind** [comment]
I'm sure there would be many (as long as they are vetted) who would step up to the plate. This way, the site remains active and ~#1 site for jekyll themes (as it is in Google right now). I believe in Jekyll and think a good theme site such as this is much needed in the community

I wouldn't mind helping out here and there, but of course the decision is up to you @mattvh

**Comment by emory** [comment]
As a largely innocent bystander I've always felt like the website and repo
needed help in order to benefit the users of jekyll as best as possible. I
can certainly appreciate pressing personal matters occupying all available
bandwidth (I've had my share lately) and I'm not in favor of a new website
and the fragmentation @mattvh refers to. I'd like to see a clear commitment
to keeping this repository and site as lively as the people sharing want it
to be.

If it's a matter of someone coordinating and providing some editorial
process to it I am willing to have a conversation about that and see how I
can help.



⤷
  You are standing in an open field west of a white house, with a boarded
front door.
  There is a small mailbox here.

**Comment by jarrekk** [comment]
I have an advice: @mattvh you can create an organization for jekyll theme then transfer this repo's owner to new organization, you can recruit some developers to contribute this repo, but we need some preparation maybe as the following link: <https://opensource.guide/> :)
Thanks.

**Comment by mattvh** [comment]
I'm going to try and set aside some time to add a new batch of contributors in the near future. @InsidiousMind, @emory, @jarrekk since you all seem keen on volunteering I'll be considering you.

It's pretty simple overall. Basically, PRs need to be reviewed to ensure that the thumbnail is correctly sized (exact dimensions) and the links are good. Some editorial leeway can be had in the theme listings, but mostly I try to avoid subjective notions of "quality." Generally, I see a theme as a theme and if the listing is good, then it's welcome.

The site is hosted on my server, and there's a process that listens for a GitHub webhook to rebuild the site as commits are merged. (Updating to a more current version of Jekyll/Ruby is on my eventual to-do list as well.) Other than that, everything is pretty casual under a "benevolent dictator for life" structure. :P 

Not sure if we really need an org or not, but it's something I'll investigate possibly.

**Comment by junlulocky** [comment]
@mattvh  Thanks a lot for your answer. If possible, please also add me to the contributor list. I am currently help @jarrekk maintaining his site. I am eager to also continue to maintain this one.

**Comment by mattvh** [comment]
Okay, I've added everyone mentioned in my previous post (plus @junlulocky) as collaborators to the repository, on a probationary basis for now. I already mentioned more or less how the process works, though I recommend skimming through some PRs that were already approved or rejected to get a better feel for it. If you have any questions on a PR, feel free to tag my name in the comments and I'll try to chime in when I can.

**Comment by InsidiousMind** [comment]
Sounds good! Thanks for working with us, @mattvh

**Comment by gynter** [comment]
Hello and welcome to all new collaborators!

I'm truly sorry for keeping this project unmaintained due lack of free time. I'm going to review all PRs again and make corrections if needed. All help is welcome :) Hopefully I'll have a bit of more time to deal with this project also :)

@InsidiousMind Currently I have made "periodic" review sprints. Basically I have merged all PRs (even the pending/illegal ones) and then made the thumbnail/fixes myself, that way the theme still gets accepted. I'm going to try to do that again.

What do You mean by personal links?

**Comment by InsidiousMind** [comment]
Thanks!

@gynter  Cool! That's not that's not a bad strategy. If some people don't respond, i'll try and do that as well

**Comment by junlulocky** [comment]
Hey @mattvh, since this project seems less responsive these
