### ISSUE TITLE
Timestamping policy?

### ISSUE THREAD

**Issue by le4ker** [mattvh/jekyllthemes#531]
Hi,

What's your policy on the timestamp of the post?
The themes are ordered in chronological order, so the timestamp is important if you want to get on the first page 😄 

Does i.e. any update of the post allow to bump the timestamp?

Thanks,
:panos

**Comment by mattvh** [comment]
Date of original submission. I don't want to open the can of worms of frequent updates to increase visibility.

**Comment by gynter** [comment]
To be honest. I have been wondering about removing the @Date@ from front matter for a while now to use only the date in file name. Main reason is because I have been spent plenty of time fixing the dates in front matter, because many submissions are copy-paste from older ones, but the @Date@ value sometimes gets overlooked by submitter. @mattvh what do You think?

**Comment by mattvh** [comment]
If you can't see any downsides to it, it works for me. It doesn't really serve much purpose.
