### ISSUE TITLE
Is this project no longer being maintained?

### ISSUE THREAD

**Issue by arnolds** [mattvh/jekyllthemes#585]
Is this project no longer being maintained? The last commit was over 30 days ago, and there are many outstanding PR's with no visible sign of progress.

I understand not everyone has the time, or that life gets in the way. But it would be a shame if this project didn't grow further, since:

- This projects website comes up first on Google when you search for "Jekyll Themes".
- Is one of the most popular, if not the most popular repository for a collection of Jekyll themes.

Could adding more collaborators solve this? I'm only aware of 4 developers who have maintained this project so far: @mattvh , @gynter, @junlulocky , @InsidiousMind .

**Comment by geraldb** [comment]
> Is one of the most popular, if not the most popular repository for a collection of Jekyll themes.

See Dr Jekyll's Themes for a more modern (better) alternative for a collection of Jekyll themes - <http://drjekyllthemes.github.io/>.

**Comment by tsjensen** [comment]
@mattvh @gynter @junlulocky @InsidiousMind I can offer to take care of the 70-something current pull requests if you grant me the necessary access. I would do so responsibly.

**Comment by tsjensen** [comment]
@mattvh @gynter @junlulocky @InsidiousMind I read some of the other open issues and it seems that this site does not run on GitHub Pages. So, since I don't have access to the server, it seems I should include in my offer to switch everything to GitHub Pages. The only thing is that at some point we'll have to change the DNS record, which would probably depend on @mattvh as well.

**Comment by mattvh** [comment]
I definitely don't plan on moving to GitHub Pages. I'm not a huge fan of tying anything to GitHub other than being a convenient repository host.

I wasn't aware that there was such a PR backlog again. (I've been busy with work and college stuff.) I'll see if I can get around to knocking some out soon. And I'm always open to adding more contributors to process PRs.

**Comment by tsjensen** [comment]
@mattvh Ok, no worries! My offer stands even without GitHub Pages.
Would you be available to do the deployment, if necessary? (It would be a bit of a let-down if I chewed through all those PRs and then stuff couldn't be deployed. 😉)

**Comment by mattvh** [comment]
It's supposed to automatically do it on a web hook. I guess I'll have to look at that too when I get a chance.

**Comment by artlogic** [comment]
Any updates on this? I was about to submit my theme, but with a backlog of 83 PRs, I'm wondering if it might be better to wait?

**Comment by mattvh** [comment]
I restarted the webhook listener, so commits should sync back to the server now and the site will be rebuilt. Merged #607 as well, since that was bothering me.

I'm just starting my first semester of my Computer Science major, so I've been absolutely swamped (with classwork and my job now, and preparations and my job before). I am, however, always interested in more volunteers who are interested in helping to process PRs. Sorry I move so slow, but I've got a lot going on.

**Comment by artlogic** [comment]
@mattvh Could you give us an idea of what's expected of a volunteer processing PRs for new themes? How many people other than yourself are currently processing themes?

**Comment by mattvh** [comment]
@artlogic It's been awhile since I've seen a commit from anyone else, so I guess just me at the moment. Mostly it's a matter of making sure thumbnails are the exact specified dimensions, and that the commit actually works (no dead links, theme is actually available to the public, not doing anything too outlandish in the body text, whatever). I try not to pass judgement on the style aspect of submissions, since that's subjective, and just accept themes if they meet the technical requirements.

**Comment by artlogic** [comment]
@mattvh I'd be happy to lend a hand with the PR backlog (at least as far as new themes go). I can't promise I can devote a ton of time to it, but if you are looking for someone to just check the things you listed, I don't mind knocking out a few here and there. Let me know what you think.

**Comment by mattvh** [comment]
@artlogic Upon some consideration, I've given you commit access. Like I said before, the review process is pretty basic. If you look at some of the existing PRs, they pretty much get tagged and commented if they're not acceptable as per the requirements (and sometimes closed and cleaned up if there isn't a timely response). Other than that, it's just approving and merging.

**Comment by tsjensen** [comment]
@artlogic Any plans?

**Comment by artlogic** [comment]
@tsjensen Working on stuff now actually!
